version: '3.3'
services:
  mse:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    image: mse
    container_name: mse
#    command: "python src/main.py --path res -m  -f trump-b.mp3"
    volumes:
      - ./result:/app/result
      - ./res:/app/res